version: '3.9'

services:
  web:
    build:
      context: .
    container_name: django_app
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata fixtures/goods/categories.json && python manage.py loaddata fixtures/goods/products.json && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DEBUG=True

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: home
      POSTGRES_PASSWORD: home
      POSTGRES_DB: home
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: