# Generated by Django 5.1.4 on 2025-02-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_review'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='Review',
        ),
    ]
