# Generated by Django 5.1.4 on 2025-03-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_review_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='products',
            name='height',
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True, unique=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='products',
            name='image_additional_1',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='ДОПОЛНИТЕЛЬНОЕ ИЗОБРАЖЕНИЕ'),
        ),
        migrations.AddField(
            model_name='products',
            name='image_additional_2',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='ДОПОЛНИТЕЛЬНОЕ ИЗОБРАЖЕНИЕ'),
        ),
        migrations.AddField(
            model_name='products',
            name='image_additional_3',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='ДОПОЛНИТЕЛЬНОЕ ИЗОБРАЖЕНИЕ'),
        ),
        migrations.AddField(
            model_name='products',
            name='length',
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True, unique=True, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='products',
            name='width',
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True, unique=True, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='ОСНОВНОЕ ИЗОБРАЖЕНИЕ'),
        ),
    ]
