# Generated by Django 5.1.4 on 2025-03-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_products_color_products_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='products',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='products',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Ширина'),
        ),
    ]
