# Generated by Django 5.1.4 on 2025-03-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_products_height_alter_products_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Высота (см)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Длина (см)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Ширина (см)'),
        ),
    ]
