# Generated by Django 5.1.4 on 2025-03-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_remove_review_image_remove_review_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Фотография 1'),
        ),
        migrations.AddField(
            model_name='review',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Фотография 2'),
        ),
        migrations.AddField(
            model_name='review',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Фотография 3'),
        ),
    ]
