# Generated by Django 5.1.4 on 2025-03-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_review_image_1_review_image_2_review_image_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='new_collection',
            field=models.BooleanField(default=False),
        ),
    ]
