# Generated by Django 5.1.4 on 2025-03-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_products_new_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='top_sales',
            field=models.BooleanField(default=False, verbose_name='Топ продаж?'),
        ),
        migrations.AlterField(
            model_name='products',
            name='new_collection',
            field=models.BooleanField(default=False, verbose_name='Новая коллекция?'),
        ),
    ]
