# Generated by Django 5.1.4 on 2025-03-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('shipped', 'Отправлен'), ('completed', 'Завершен'), ('canceled', 'Отменён')], default='new', max_length=15, verbose_name='Статус заказа'),
        ),
    ]
